const actions = {
    GET_DATA_MAN: "GET_DATA_MAN",
    GET_DATA_MAN_SUCCESS: "GET_DATA_MAN_SUCCESS",
    GET_DELTAI: "GET_DELTAI",
    GET_DELTAI_SUCCESS: "GET_DELTAI_SUCCESS",
    GET_ORDER: "GET_ORDER",
    GET_ORDER_SUCCESS: "GET_ORDER_SUCCESS",
    ADD_CART:"ADD_CART",
    ADD_CART_SUCCESS:"ADD_CART_SUCCESS",
    DELETE_CART:"DELETE_CART",
    GET_INFO: "GET_INFO",
    GET_INFO_SUCCESS: "GET_INFO_SUCCESS",
    ADD_INFO: "ADD_INFO",
    ADD_INFO_SUCCESS: "ADD_INFO_SUCCESS",
  };
  export default actions;
  